### ISSUE TITLE
where is the regex file location to pull request ?

### ISSUE THREAD

**Issue by ayadim** [CYS4srl/CYS4-SensitiveDiscoverer#7]
hi,
if I want to add my regular expression to your list which location I should add to it? 
target/classes/regex.json
or 
src/main/java/cys4/resources/regex.json

regards

**Comment by LorenzoCoppi-cys4** [comment]
Hi @ayadim, the correct place would be inside the `src/` folder. The `target/` folder is for maven's build output files.

We had a look at your regex posted in #2. In some cases we tested it on, it had a few too many false positives. It's planned to be added, maybe with some minor tweaks.

Since we are currently working on improving the regex list, if you could add the regex to this issue, we'll add it in the upcoming changes and track all updates directly here.

**Comment by ayadim** [comment]
here is the improved version.

(?i)(([a-z0-9]+)[-|_])?(key|password|passwd|pass|pwd|private|credential|auth|cred|creds|secret|access|token)([-|_][a-z]+)?(\s)*(:|=)+

you can see examples that i work on them here :   https://regex101.com/r/QhNFBA/

**Comment by ayadim** [comment]
hi if there's other cases tht my regular expression doesn't not match them ... just provide me with examples and i will do a try . 
regards
